inherit: true

tools:
    external_code_coverage:
        timeout: 3600
    php_code_sniffer: true
    php_cpd: true
    php_cs_fixer: true
    php_loc: true
    php_mess_detector: true
    php_pdepend: true
    php_analyzer: true
    sensiolabs_security_checker: true

filter:
    excluded_paths:
        - 'web/skins/*'
        - 'skins/10h16/*'
        - 'node_modules/*'
        - 'tests/*'
    dependency_paths:
        - 'vendor/'

build:
    nodes:
        analysis:
            tests:
                override:
                - php-scrutinizer-run
    tests:
        override:
        - true


