# This file is used during unit tests and overrides campaign configurations
#
# All campaigns *MUST* be inactive to force the tests using the default code paths
# Unit tests that test campaign features might override the campaign state


# Until https://phabricator.wikimedia.org/T163452 is resolved,
# we must force the unit tests to use the `test` skin.
skins:
  active: false
  buckets:
     - "test"
  default_bucket: "test"

donation_address:
  active: false
